name: ci

on:
  push:
    branches:
      - 'main'
  schedule:
    # Every 1st of the month
    - cron: "0 0 1 */1 *"
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare
        id: prep
        run: |
          DOCKER_IMAGE=overbit/kaniko-node
          TAGS="${DOCKER_IMAGE}:${GITHUB_SHA::6}"
          TAGS="$TAGS,${DOCKER_IMAGE}:latest"
          echo ::set-output name=image::${DOCKER_IMAGE}
          echo ::set-output name=gitsha::${GITHUB_SHA::6}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push LTS
        id: docker_build_lts
        uses: docker/build-push-action@v2
        with:
          build-args: NODE_VERSION=LTS
          push: true
          tags: |
              ${{ steps.prep.outputs.image }}:lts
              ${{ steps.prep.outputs.image }}:lts-${{ steps.prep.outputs.gitsha }}
      -
        name: Build and push CURRENT
        id: docker_build_current
        uses: docker/build-push-action@v2
        with:
          build-args: NODE_VERSION=CURRENT
          push: true
          tags: |
              ${{ steps.prep.outputs.image }}:latest
              ${{ steps.prep.outputs.image }}:current-${{ steps.prep.outputs.gitsha }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
